# Generated by Django 2.2.8 on 2020-02-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Received'), (1, 'Sent')], default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(max_length=255)),
                ('measure', models.DecimalField(decimal_places=3, max_digits=7)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webApp.Messages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumidityMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(max_length=255)),
                ('measure', models.DecimalField(decimal_places=3, max_digits=7)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webApp.Messages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceActivationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(max_length=255)),
                ('measure', models.DecimalField(decimal_places=3, max_digits=7)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webApp.Messages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
