# Generated by Django 2.2.8 on 2020-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceactivationlog',
            name='measure',
            field=models.CharField(max_length=255),
        ),
    ]
